# SMDS model configuration

# Model parameters
model:
  state_dim: 10
  emission_dim: 100
  input_dim: 0
  num_conditions: 1
  dynamics_cov_type: "diagonal"
  emissions_cov_type: "diagonal"
  has_dynamics_bias: true
  has_emissions_bias: false
  ekf_mode: "cov"
  fix_tau: false
  tau_per_dim: true
  emissions_cov_eps: 1e-2
  base_subspace_type: "random"
  initial_velocity_cov: 1e-4
  init_tau: 1e-6
  max_tau: 1e-4

# Training parameters
training:
  num_iters: 200
  run_velocity_smoother: false
  print_ll: true
  velocity_smoother_method: "ekf"
  ekf_num_iters: 1

# Evaluation parameters
evaluation:
  compute_r2: true
  compute_cosmoothing: false
  cosmoothing_mask_ratio: 0.8  # Use 80% of dimensions for held-in
  # cosmoothing_mask_file: "path/to/mask.npy"  # Alternative: load mask from file
  method: "marginal"  # "marginal" or "joint"

# Data parameters
data:
  path: "/oak/stanford/groups/swl1/hdlee/crcns/U201202_01"
  block_size: 1

# Wandb configuration
wandb:
  project: "smds"
  entity: null  # Your wandb username or team
  mode: "online"  # "online", "offline", or "disabled"

# Global parameters
seed: 42
use_wandb: true
eval_only: false
pretrained_model: null 