command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

# Wandb configuration
program: /home/groups/swl1/hdlee/representational_drift/scripts/train_smds_simulated.py
project: smds
name: simulated_sweep
method: grid

parameters:
  # Seed parameter
  seed:
    values: [3468]
  
  # Sweep parameters
  model.type:
    values: ["lds"]
  model.state_dim:
    values: [5, 10, 15, 20, 25, 30, 35, 40]
  model.ekf_mode:
    value: "cov"
  model.tau_per_dim:
    value: true
  model.tau_per_axis:
    value: false
    
  # Default configuration parameters
  model.has_dynamics_bias:
    value: true
  model.has_emissions_bias:
    value: false
  model.emissions_cov_eps:
    value: 1e-9
  model.base_subspace_type:
    values: ["random"]
  model.initial_velocity_cov:
    value: 1e-6
  model.fix_initial_velocity_cov:
    value: false
  model.init_tau:
    values: [1e-6]
  model.fix_tau:
    value: false
  model.max_tau:
    value: 1e-3
  model.tau_concentration:
    values: [1e0]
  model.tau_scale:
    values: [1e-6]
  
  # Training parameters
  training.run_velocity_smoother:
    value: false
  training.print_ll:
    value: true
  training.velocity_smoother_method:
    value: "ekf"
  training.ekf_num_iters:
    value: 1
  training.num_iters:
    value: 300
  training.smds_test_state_dim_bound:
    value: 4

  eval.ekf_num_iters:
    value: 1

  # Data parameters
  data.block_size:
    value: 1
  data.state_dim:
    value: 15
  data.emission_dim:
    value: 50
  data.num_trials:
    value: 750
  data.num_conditions:
    value: 4
  data.num_timesteps:
    value: 30
  data.velocity_type:
    values: ["sine"]
  data.regenerate_data:
    value: true