command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

# Wandb configuration
program: /home/groups/swl1/hdlee/representational_drift/scripts/train_fig4.py
project: smds
name: alm_sweep
method: grid

parameters:
  # Seed parameter
  seed:
    # values: [2626]
    values: [81357]
  model_seed:
    values: [2014]
  
  # Sweep parameters
  model.type:
    values: ["smds"]
  model.state_dim:
    # values: [40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
    # values: [30, 32, 34, 36, 38, 40]
    # values: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
    # values: [2, 3, 4, 5]#, 6, 7, 8, 9, 10]
    values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  model.ekf_mode:
    value: "cov"
  model.tau_per_dim:
    value: true
  model.tau_per_axis:
    value: false
  training.num_iters:
    value: 600
    
  # Default configuration parameters
  model.initialize_with_lds:
    values: [false]
  model.has_dynamics_bias:
    value: true
  model.has_emissions_bias:
    value: false
  model.emissions_cov_eps:
    values: [5e-3]
  model.base_subspace_type:
    values: ["pca"]
  model.initial_velocity_cov:
    values: [1e-4]
  model.fix_initial_velocity_cov:
    value: false
  model.init_tau:
    values: [1e-5, 5e-6, 1e-6]
    # values: [1e-5]
  model.fix_tau:
    value: false
  model.max_tau:
    values: [1e-4]
  model.fix_scale:
    values: [true]
  model.initial_velocity_covariance_concentration:
    values: [1e-4]
  model.initial_velocity_covariance_scale:
    values: [1e-4]
  model.tau_concentration:
    values: [1e-6, 1e-5, 1e-3, 1e-1]
    # values: [1e-5]
  model.tau_scale:
    values: [1e-4, 1e-5, 1e-6]
    # values: [1e-2, 1e-3, 5e-4]
    # values: [1e-5]

  # Training parameters
  training.run_velocity_smoother:
    value: false
  training.print_ll:
    value: true
  training.velocity_smoother_method:
    value: "ekf"
  training.ekf_num_iters:
    value: 1
  training.num_iters_smds_init_with_lds:
    value: 300

  eval.ekf_num_iters:
    value: 1

  # Data parameters
  data.path:
    value: "/home/groups/swl1/hdlee/nast/neurips_2025"
  data.block_size:
    # value: 8
    value: 1
  data.standardize:
    value: true
