command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

# Wandb configuration
program: /home/groups/swl1/hdlee/representational_drift/scripts/train.py
project: smds
name: U201202_01_sweep
method: grid
use_wandb: true

parameters:
  # Seed parameter
  seed:
    values: [16645]
  
  # Sweep parameters
  model.type:
    values: ["smds", "lds"]
  model.state_dim:
    values: [12, 16, 20]
  model.ekf_mode:
    value: "cov"
  model.tau_per_dim:
    value: true
  training.num_iters:
    value: 300
    
  # Default configuration parameters
  model.has_dynamics_bias:
    value: true
  model.has_emissions_bias:
    value: false
  model.emissions_cov_eps:
    value: 1e-2
  model.base_subspace_type:
    values: ["pca"]
  model.initial_velocity_cov:
    value: 1e-6
  model.init_tau:
    value: 1e-6
  model.fix_tau:
    value: false
  model.max_tau:
    value: 1e-4
  
  # Training parameters
  training.run_velocity_smoother:
    value: false
  training.print_ll:
    value: true
  training.velocity_smoother_method:
    value: "ekf"
  training.ekf_num_iters:
    value: 2

  eval.ekf_num_iters:
    value: 2

  # Data parameters
  data.path:
    value: "/oak/stanford/groups/swl1/hdlee/crcns/U201202_01"
  data.block_size:
    value: 1
  data.standardize:
    value: true
