command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

# Wandb configuration
program: /home/groups/swl1/hdlee/representational_drift/scripts/train.py
project: smds
name: U201202_01_sweep
method: grid

parameters:
  # Seed parameter
  seed:
    values: [10796, 781899, 16441, 51407, 203875]

  model_seed:
    values: [1234]
  
  # Sweep parameters
  model.type:
    values: ["smds"]
  model.state_dim:
    values: [5, 10, 15, 20, 25, 30, 35]
  model.ekf_mode:
    value: "cov"
  model.tau_per_dim:
    value: true
  model.tau_per_axis:
    value: false
  training.num_iters:
    value: 300
    
  # Default configuration parameters
  model.initialize_with_lds:
    values: [false]
  model.has_dynamics_bias:
    value: true
  model.has_emissions_bias:
    value: false
  model.emissions_cov_eps:
    values: [5e-3, 4e-3]
  model.base_subspace_type:
    values: ["pca"]
  model.initial_velocity_cov:
    values: [1e-4]
  model.fix_initial_velocity_cov:
    value: false
  model.init_tau:
    values: [2e-5, 1e-5, 7e-6, 5e-6]
  model.fix_tau:
    value: false
  model.max_tau:
    values: [1e-4]
  model.fix_scale:
    values: [true]
  model.initial_velocity_covariance_concentration:
    values: [1e-4]
  model.initial_velocity_covariance_scale:
    values: [1e-4]
  model.tau_concentration:
    values: [1e-3, 1e-2, 1e-1]
  model.tau_scale:
    values: [1e-6]
  
  # Training parameters
  training.run_velocity_smoother:
    value: false
  training.print_ll:
    value: true
  training.velocity_smoother_method:
    value: "ekf"
  training.ekf_num_iters:
    value: 1
  training.num_iters_smds_init_with_lds:
    value: 300

  eval.ekf_num_iters:
    value: 1

  # Data parameters
  data.path:
    value: "/oak/stanford/groups/swl1/hdlee/crcns/U201202_01"
  data.block_size:
    value: 8
  data.standardize:
    value: true
